version: '3.8'

services:
  parser:
    build: .
    container_name: apify-parser
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
